def get_data(session: str | None=None, day: int | None =None, year: int | None =None, block: bool=False) -> str:...
def most_recent_year() -> int:...
def current_day() -> int:...
def get_day_and_year() -> tuple[int, int | None]:...